#! /bin/sh
# example wallpaper script
# this uses xwallpaper and random_run from ports

# choose a random portrait pic
pic1=`rr -1pl portrait`
# and a random landscape pic
pic2=`rr -1pl landscape`
xwallpaper --output HDMI-0 --zoom $pic1 --output VGA-0 --zoom $pic2
