#! /bin/sh

# this is the small script I use to build releases
set -e
V=HEAD
if [ $# -gt 0 ]
then
	V=$1
fi
D=openbsd-backgrounds-$V
rm -rf openbsd-backgrounds-*
git archive --prefix=$D/ --format=tar HEAD|tar xvf -
cd $D
pwd
rm -f portrait landscape
gm mogrify -resize '2560x1600>^' `cat landscape.list`
gm mogrify -resize '1600x2560>^' `cat portrait.list`
for o in landscape portrait
do
    cat $o.list|while read i; do 
	j=`dirname $i|sed -e s/pictures/$o-pictures/`
	mkdir -p $j
	mv $i $j
    done
done
perl mklist
rm -rf pictures landscape.list portrait.list
cd ..
tar zcf $D.tar.gz $D
